### PR TITLE
vulkaninfo: Fix issue 202

### LINKED ISSUE #202: vulkaninfo warnings in VS2015 build
When build on Windows VS2015 using:
```
mkdir build
cd build
cmake -A x64 ..
cmake --build .
```
the following warning result:
```
vulkaninfo.c(4953): warning C4996: '_snprintf': This function or variable may be unsafe. Consider using _snprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS.
vulkaninfo.c(5564): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS.
vulkaninfo.c(5651): warning C4996: '_snprintf': This function or variable may be unsafe. Consider using _snprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS.
vulkaninfo.c(5652): warning C4996: '_snprintf': This function or variable may be unsafe. Consider using _snprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS.
```

### PR DESCRIPTION
**Pull request by jeremyk-lunarg**
Vulkaninfo was replacing function `snprintf`
with function `_snprintf` on windows.

This seems to be for backwards compatiblity
with VS2013.

`_snprintf` is considered deprecated in VS2015
as `snprintf` is properly implemented.

Since we are dropping compatibility with VS2013 it
seems like this replacement can be removed.

Complete removal of the pre-processor command
that replaces `snprintf` with `_snprintf` seems to cause
problems with AppVeyor.  Instead I now replace `snprintf`
with `_snprintf_s`.

Hopefully a future commit can remove this completely.

Fixes #202

### CODE REVIEW

**Comment by mikew-lunarg** [comment]
@jeremyk-lunarg That addresses the _snprintf warning, but not the fopen warning.

```
vulkaninfo.c(5563): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. 
```

**Comment by jeremyk-lunarg** [comment]
@mikew-lunarg  Updated.

File: vulkaninfo/vulkaninfo.c [hunk 1]
```diff
@@ -5561,7 +5560,11 @@ int main(int argc, char **argv) {
     AppCreateInstance(&inst);
 
     if (html_output) {
+#ifdef _WIN32
+        fopen_s(&out, "vulkaninfo.html", "w");
```
Comment (mikew-lunarg) [inline vulkaninfo/vulkaninfo.c]: Can't tell from MSDN docs if failure will assign out=nullptr, the docs say to check the return value.  So perhaps something like
```
if(fopen_s(&out, "vulkaninfo.html", "w") !=0) out=nullptr;
```

**Comment by jeremyk-lunarg** [comment]
@mikew-lunarg Update.  The Microsoft docs confirm that `out` does not get set to `NULL` on failure.
Thanks for catching that.

Also, made a few changes to hopefully fix that AppVeyor failure.

File: vulkaninfo/vulkaninfo.c [hunk 2]
```diff
@@ -5561,7 +5564,11 @@ int main(int argc, char **argv) {
     AppCreateInstance(&inst);
 
     if (html_output) {
+#ifdef _WIN32
+        if (fopen_s(&out, "vulkaninfo.html", "w") != 0) out = NULL;
```
Comment (mikew-lunarg) [inline vulkaninfo/vulkaninfo.c]: I think this needs a clang-format, then LGTM
